project_id = "rpaqcsnojgdmndbqthov"

[functions.send-longevity-report]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.subscribe-to-mailing-list]
verify_jwt = false