// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylurniqxyjpjzriqnkbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsdXJuaXF4eWpwanpyaXFua2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDcyMDUsImV4cCI6MjA2NjgyMzIwNX0.ym0Qy-5yVlg2pnBVdLlRqOkJbyw7KZOGOgkmrW8BW5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});